[build]
  command = "gatsby build --prefix-paths"
  publish = "blog/public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "/*"
  to = "/blog"
  status = 200
  force = true
  headers = {X-From = "Netlify"}